### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by Edtigoza** [chamilo/stats-page#1]
Hi, how can I install it,
- I put it in the plugin folder, and it did not work,
- try to open it by the browser and it did not work, 
- do I must edit the configuration.php?
- is there any instruction to install?

**Comment by ywarnier** [comment]
Hi, this is not a plugin, this is the code for the stats page of Chamilo (https://stats.chamilo.org) which depends on data that we track. It is public in case it can serve as basis for others to implement their own tracking system, but it's not something you add to Chamilo.
